IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BOOKING_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[BOOKING_DETAILS]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO


CREATE TABLE [dbo].[BOOKING_DETAILS](
	hall_sk_seq INT NOT NULL,
	customer_sk_seq INT NOT NULL,
	booking_date date NOT NULL,
	booking_status [varchar](15) NOT NULL,
	active_ind char(1) NOT NULL,
	create_account_sk_seq int NOT NULL,
	create_datetime datetime NOT NULL,
	modify_account_sk_seq int NOT NULL,
	modify_datetime datetime NOT NULL
) ON [PRIMARY]

ALTER TABLE dbo.BOOKING_DETAILS ADD CONSTRAINT
	PK_booking PRIMARY KEY CLUSTERED 
	(
	hall_sk_seq, customer_sk_seq, booking_date
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.BOOKING_DETAILS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


